### ISSUE TITLE
And another:

### ISSUE THREAD

**Issue by mingwandroid** [conda-forge/sqlalchemy-utils-feedstock#10]
https://github.com/conda-forge/sqlalchemy-utils-feedstock/blob/3efafd4d19cd5a88a9cc67655b7d68e0b152ac06/recipe/meta.yaml#L36

**Comment by pmlandwehr** [comment]
`colour` is provided by the [`colour-science` feedstock](https://github.com/conda-forge/colour-science-feedstock).

**Comment by mingwandroid** [comment]
No, it isn't https://github.com/conda-forge/colour-science-feedstock/blob/master/recipe/meta.yaml#L1

**Comment by mingwandroid** [comment]
The `colour-science` package provides an import called `colour` but you are supposed to list package names in your dependencies not imports, so here you need to change this to `colour-science`.

Please reopen this.
