### ISSUE TITLE
Recipe should build from source package, not wheels

### ISSUE THREAD

**Issue by igortg** [conda-forge/sqlalchemy-utils-feedstock#47]
The latest version of **sqlalchemy-utils** was published without the source package. Recipe was temporarily changed to build from the wheel, but that must be undone as soon as the source package becomes available.

https://github.com/kvesteri/sqlalchemy-utils/issues/512

**Comment by jarkkorantala** [comment]
The source package is now available with sqlalchemy-utils 0.37.1: https://pypi.org/project/SQLAlchemy-Utils/#files

**Comment by lvoliveira** [comment]
Closing this because it was solved in #49
