### ISSUE TITLE
And another missing one.

### ISSUE THREAD

**Issue by mingwandroid** [conda-forge/sqlalchemy-utils-feedstock#9]
https://github.com/conda-forge/sqlalchemy-utils-feedstock/blob/3efafd4d19cd5a88a9cc67655b7d68e0b152ac06/recipe/meta.yaml#L35

**Comment by pmlandwehr** [comment]
the default distribution provide `passlib 1.7.1`, so at present this isn't a concern for me or something that should block installation.
